version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./public/files:/usr/share/nginx/html/files
    restart: unless-stopped
